name: CI Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # Шаг 1: Получение кода
            - name: Checkout code
              uses: actions/checkout@v2

            # Шаг 2: Установка Node.js
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "16"

            # Шаг 3: Установка зависимостей
            - name: Install dependencies
              run: npm install

            # Шаг 5: Сборка приложения
            - name: Build
              run: npm run build
            
    deploy: 
        runs-on: ubuntu-latest

        steps:
            # Шаг 1: Получение кода
            - name: Connect to Host and Pull Updates
              env:
                HOST: ${{ secrets.HOST_IP2 }}
                USERNAME: ${{ secrets.HOST_LOGIN }}
                PASSWORD: ${{ secrets.HOST_PASSWORD }}
              run: |
                sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "cd /var/www/apps/counter && git pull"

            - name: Install Dependencies
              run: |
                "npm install"

            - name: Rebuild Project
              run: |
                "npm run build"
